version: "3.5"
services:
  ball-prod:
    image: ball-prod
    container_name: ball-prod
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "172.50.11.1:8080:80"
    networks:
      ball-prod_net:
        ipv4_address: 172.50.11.11

networks:
  ball-prod_net:
    ipam:
      driver: default
      config:
        - subnet: "172.50.11.0/24"
